### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by kuimovvg** [klesarev/axios-rus-docs#3]
Ошибка в заголовке "Дополнительная ифнормация"
https://github.com/klesarev/axios-rus-docs/tree/master/docs#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B8%D1%84%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F

**Comment by klesarev** [comment]
Спасибо, исправил.
